basiclogin/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.contrib.auth import views
from log.forms import LoginForm

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url('', include('log.urls')),
    url(r'^login/$', views.login, {'template_name': 'login.html',
                                   'authentication_form': LoginForm}, name="login"),
    url(r'^logout/$', views.logout, {'next_page': '/login'}, name="logout"),
]

log/urls.py
from django.conf.urls import url
from . import views

app_name = 'log'
urlpatterns = [
    url(r'^$', views.home, name='home'),
    url(r'^register/$', views.register, name='register'),
]

log/models.py
from django.db import models

# Create your models here.

log/forms.py
from django.contrib.auth.forms import AuthenticationForm
from django.contrib.auth.models import User
from django import forms

class LoginForm(AuthenticationForm):
    username = forms.CharField(label="Username", max_length=30,
                               widget=forms.TextInput(attrs={'class': 'form-control', 'name': 'username'}))
    password = forms.CharField(label="Password", max_length=30,
                               widget=forms.TextInput(attrs={'class': 'form-control', 'name': 'password', 'type': 'password'}))

class RegisterForm(forms.Form):
    username = forms.CharField(label="Username", max_length=30,
                               widget=forms.TextInput(attrs={'class': 'form-control', 'name': 'username'}))
    email = forms.CharField(label="Email", max_length=30,
                            widget=forms.TextInput(attrs={'class': 'form-control', 'name': 'username'}))
    password = forms.CharField(label="Password", max_length=30,
                               widget=forms.TextInput(attrs={'class': 'form-control', 'name': 'password', 'type': 'password'}))
    password_again = forms.CharField(label="Repeat your password", max_length=30,
                               widget=forms.TextInput(attrs={'class': 'form-control', 'name': 'password', 'type': 'password'}))

log/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.decorators import login_required
from django.contrib.auth.models import User
from django.contrib.auth import authenticate, login
from log.forms import RegisterForm

@login_required(login_url='login')
def home(request):
    return render(request, "home.html")

def register(request):
    if request.method == "POST":
        username = request.POST.get('username', None)
        email = request.POST.get('email', None)
        password = request.POST.get('password', None)
        password_again = request.POST.get('password_again', None)
        if password != password_again:
            register = RegisterForm()
            return render(request, 'register.html', {
                'register_form': register,
                'error_message': "Passwords not match",
            })
        user, created = User.objects.get_or_create(username=username, email=email)
        if created:
            user.set_password(password)
            user.save()
            user = authenticate(username=username, password=password)
            login(request, user)
            return redirect("/")
        return redirect("/login")

    else:
        register = RegisterForm()
        return render(request, "register.html", {'register_form': register})

templates/base.html
{% load staticfiles %}

<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Basic Login</title>
    <link href="{% static 'bootstrap/css/bootstrap.min.css' %}" rel="stylesheet">
    <link href="{% static 'css/base.css' %}" rel="stylesheet">
  </head>
  <body>
    <nav class="navbar navbar-default">
      <div class="container">
        <div class="navbar-header">
          <a href="{% url 'log:home' %}" class="navbar-brand" id="header-logo">Basic Login</a>
        </div>
        {% block logout %}
          <a href="{% url 'log:register' %}">
            <button type="button" class="btn btn-primary navbar-btn navbar-right">Register</button>
          </a>
        {% endblock %}
      </div>
    </nav>
    {% block content %}
    {% endblock %}

    <script src = "{% static 'bootstrap/js/bootstrap.min.js' %}"></script>
  </body>
</html>

templates/home.html
{% extends 'base.html' %}

{% block logout %}
  <a href="{% url 'logout' %}">
    <button type="button" class="btn btn-warning navbar-btn navbar-right">Logout</button>
  </a>
{% endblock %}

{% block content %}
  <div class="container">
    <div class="row">
      <h1>HI, {{ user.username }}!!</h1>
      <p>Welcome</p>
    </div>
  </div>
{% endblock %}

templates/login.html
{% extends 'base.html' %}

{% block content %}
<div class="container">
  <div class="row">
    <div class="col-md-4 col-md-offset-4">
      <div class="login-panel panel panel-default">
        <div class="panel-heading">
          <h3 class="panel-title">Login</h3>
        </div>
        <div class="panel-body">
          <form method="post" action="{% url 'login' %}">
            {% csrf_token %}
            <p class="bs-component">
              <table>
                <tr>
                  <td>{{ form.username.label_tag }}</td>
                  <td>{{ form.username }}</td>
                </tr>
                <tr>
                  <td>{{ form.password.label_tag }}</td>
                  <td>{{ form.password }}</td>
                </tr>
              </table>
            </p>
            <p class="bs-component">
              <center>
                {% if form.errors %}
                  <p><font color=red>Your username and password didn't
                    match. Please try again.</font></p>
                {% endif %}
                <input class="btn btn-success" type="submit" value="Login" />
              </center>
            </p>
              <input type="hidden" name="next" value="{{ next }}" />
          </form>
        </div>
      </div>
    </div>
  </div>
</div>
{% endblock %}

templates/register.html
{% extends 'base.html' %}

{% block content %}

<div class="container">
  <div class="row">
    <div class="col-md-4 col-md-offset-4">
      <div class="login-panel panel panel-default">
        <div class="panel-heading">
          <h3 class="panel-title">Register</h3>
        </div>
        <div class="panel-body">
          <form method="post" action="{% url 'log:register' %}">
            {% csrf_token %}
            <p class="bs-component">
              <table>
                <tr>
                  <td>{{ register_form.username.label_tag }}</td>
                  <td>{{ register_form.username }}</td>
                </tr>
                <tr>
                  <td>{{ register_form.email.label_tag }}</td>
                  <td>{{ register_form.email }}</td>
                </tr>
                <tr>
                  <td>{{ register_form.password.label_tag }}</td>
                  <td>{{ register_form.password }}</td>
                </tr>
                <tr>
                  <td>{{ register_form.password_again.label_tag }}</td>
                  <td>{{ register_form.password_again }}</td>
                </tr>
              </table>
            </p>
            <p class="bs-component">
              <center>
                {% if error_message %}
                  <p>
                    <font color="red"><strong>{{ error_message }}</strong></font>
                  </p>
                {% endif %}
                <input class="btn btn-primary" type="submit" value="Register" />
              </center>
            </p>
          </form>
        </div>
      </div>
    </div>
  </div>
</div>
{% endblock %}